# Generated by Django 3.2.6 on 2023-01-12 11:48

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BelievedCustomers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='Customers/%Y-Year/%m-Month/')),
            ],
            options={
                'verbose_name': 'Bizga ishonch bildirgan',
                'verbose_name_plural': 'Bizga ishonch bildirganlar',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('number', models.PositiveIntegerField()),
                ('contact_type', models.CharField(choices=[('Ish Yuzasidan', 'Ish Yuzasidan'), ('Kamchiliklar Yuzasidan', 'Kamchiliklar Yuzasidan'), ('Takliflar Yuzasidan', 'Takliflar Yuzasidan'), ('Boshqa Masalada', 'Boshqa Masalada')], default='Ish Yuzasidan', max_length=555)),
                ('message', models.TextField(default='Assalomu Alaikum, ')),
            ],
            options={
                'verbose_name': 'Habar',
                'verbose_name_plural': 'Habarlar',
            },
        ),
        migrations.CreateModel(
            name='OurWorks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('author', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='OurWorks/%Y-Year/%m-Month')),
                ('url', models.URLField(max_length=300)),
                ('category', models.CharField(choices=[('web', 'web'), ('mobile', 'mobile'), ('desktop', 'desktop')], max_length=200)),
                ('description', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name_plural': 'Bizning loyihalarimiz',
            },
        ),
    ]
